### ISSUE TITLE
Missing `language-server-bitbake/tree-sitter-bitbake.wasm`

### ISSUE THREAD

**Issue by uyha** [yoctoproject/vscode-bitbake#308] opened 2024-08-20 10:56 UTC
I'm trying to use this language server with neovim but run into an issue saying it cannot find `language-server-bitbake/tree-sitter-bitbake.wasm`. I checked the source code and see that `tree-sitter-bitbake.wasm` and `tree-sitter-bash.wasm` are removed during the build process. How should I generate them?

**Comment by deribaucourt** [comment] 2024-08-21 07:51
To package the server, we do:
```
npm run clean
npm install
npm run fetch
npm run compile
cd server
npm pack
```
This produces a .tgz which does contain the .wasm files on the latest `staging` branch. They are used to parse bitbake files to provide the various language features. However the current release on the NPM registry is indeed broken! When installing through the registry, you should install the previous version until we deploy the next one which will be fixed:
```
npm install -g language-server-bitbake@2.5.0
```
I am concerned about how the .wasm could have been removed in our latest release. Can you tell me which commit you are building? And which build script is removing them? I see they are properly marked as exceptions to keep in the `server/.npmignore` file (`!` means do keep the file in the package).

Thanks!

**Comment by uyha** [comment] 2024-08-21 07:53
I installed them all via `npm`, here is the tree
```
├── language-server-bitbake@2.6.0
├── npm@10.8.2
├── tree-sitter-bash@0.21.0
└── tree-sitter-bitbake@1.1.0
```

**Comment by uyha** [comment] 2024-08-21 07:58
As for which script removes them, I'm not sure, I just assume that being the case since they do not exist in the final packaging.

**Comment by deribaucourt** [comment] 2024-08-21 08:00
When installing through npm you do not need to install the tree-sitter dependencies manually, or copy them into `language-server-bitbake`. They should be present in our package as .wasm files. I recommend that you install the previous 2.5.0 release with the command `npm install -g language-server-bitbake@2.5.0` which was properly bundled.

It looks like just the 2.6.0 packaging is missing them. If I rebuild one from `staging` They are present. I know an error happened in the 2.6.0 NPM release pipeline and I had to manually fix things. I probably improperly published the package.
I'm going to makr 2.5.0 as the default version untill we have deployed a 2.7.0.

**Comment by deribaucourt** [comment] 2024-08-21 08:13
2.5.0 has been reverted as the latest version. It will automatically be selected if you re-install:
```bitbake
npm remove -g language-server-bitbake 
npm install -g language-server-bitbake 
```

I also want to make sure the packaging of the next release won't be affected. It turns out you were right, our CI build script was responsible for not packaging the .wasm file! I'm going to make a PR for that to close the issue.

Thank you very much for reporting this regression!

**Closed** 2024-08-23 07:36 UTC
