### ISSUE TITLE
devtool workspace scan fails on older Yocto version 

### ISSUE THREAD

**Issue by joguy56** [yoctoproject/vscode-bitbake#337] opened 2024-10-04 15:55 UTC
When modifying a recipe using the --no-extract because of using an external directory, this directory is not listed in the devtool workspace.

Seems to be logic as it seems to be directly linked with the default sdk directory.

But, if devtool can manage external directories for modified recipes, I expect that the plugin does exactly the same, and is able to list modified recipes even if there were not extracted in the internal workspace.

It would be great to see it directly from vscode as if the usual sdk workspace was used !

**Comment by deribaucourt** [comment] 2024-10-09 14:49
Thanks for this new issue report!
When clicking the devtool recipe name in the devtool side panel, we open the workspace reported by `devtool status`. I guess this is not the right directory with the `--no-extract` option.
I'll have a look at reproducing it and try fixing it.
I'll let you know when I'm done.

**Comment by deribaucourt** [comment] 2024-11-19 17:01
Hello @joguy56 
Sorry for the delay, I finally had the time to test this. I did run `devtool modify --no-extract busybox <some-external-dir>` and the plugin did properly parse `devtool status output` to show it in the devtool workspaces tree view. However, **make sure to rescan the project** after you manually have input a devtool modify command.

We don't automatically re-scan the project because it is slow. We could add a file watcher in the workspace appends for that but I think manually pressing the "Bitbake: Rescan Project" is fine.

Let me know if re-starting a scan solved your issue.
Thanks!

**Comment by joguy56** [comment] 2024-11-20 12:19
Hello @deribaucourt !

Indeed I see that the bbappend is pointing to the right sourctree. If I build the recipe from the devtool workspace wheel, I builds the right recipe at the external sourctree.

Now, if I click on the foam workspace, vscode don’t manage the fact that it is an external source tree, and it believes that it is a kind of docker container.

![image](https://github.com/user-attachments/assets/1a3ebd12-c567-4bcf-9afd-656a0c16cc76)

See the capture I get when I click on the workspace to open a new vscode instance inside it.

Please, let me know if you need any further informations.

Jonathan

**Comment by deribaucourt** [comment] 2024-11-20 12:28
Could you provide more information on this error?

1. Does the path reported in this error message exist on your host?
2. Is VS Code susceptible to have permission errors when trying to access that path?
3. You are not using docker containers, right?
4. What is the output of "devtool status"?
5. You can turn on the extension's verbosity through the setting `bitbake.loggingLevel`, then please capture the logs in the `Output -> BitBake` window (next to terminals)

Thanks

**Comment by joguy56** [comment] 2024-11-20 12:41
![image](https://github.com/user-attachments/assets/d0f670d3-4b27-4061-811a-4653cf7d1e51)

![image](https://github.com/user-attachments/assets/36c79aa7-3ad4-40c6-8ef9-0f452b6c3a59)

You can see that the recipe is correctly appended in workspace.

I could send you a log file but only in private please.

**Comment by deribaucourt** [comment] 2024-11-20 16:00
Looking at your log, it seems our scan aborts because of the following error:
```
Executing Bitbake command with /bin/bash in /home/jguyot/work/rfsw/esdk/sdk: bitbake-getvar OVERRIDES
/bin/bash: bitbake-getvar: command not found
Failed to execute bitbake command: bitbake-getvar OVERRIDES
scanning of project is aborted: Error: Failed to execute bitbake command: bitbake-getvar OVERRIDES
```
It should have been reported to you in the "Terminal" view. This error is typical of using older Yocto versions. We try to align our support with the active Yocto versions defined on the official wiki: https://wiki.yoctoproject.org/wiki/Releases

The initial `foam` workspace is likely shown because at some point you created it through our GUI.

Could you confirm which Yocto version you are using?

**Comment by deribaucourt** [comment] 2024-11-21 09:05
Closing this as a duplicate of #202

**Closed by deribaucourt** 2024-11-21 09:05 UTC
Labels: bug
